# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a996ea61e131d4bf2f3e1fab0def59f4f435102d3d53418520d92f5b18651e2373991f8dd8de32914ce3bd14b566fc038c132a2e0d48920f2d2c7d4b4295835

test:
  secret_key_base: a525aa827839e30885d26c586f137a274366f2046f962591952df6984cc6c6314b55f665742e3e2f636d6bf6761f03e838fc3b7ce92feb95572354cdcba7eb2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
